name: Semgrep Analysis
env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET
on: push

permissions:
  contents: read
  security-events: write
  pages: write
  id-token: write

jobs:
  security:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      # - name: Configurando la versión de NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}  
      - name: Semgrep scan
        run: semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off
      
      - name: Semgrep scan JSON for HTML report
        run: semgrep scan --config="p/default" --json --output=semgrep.json --metrics=off
      
      - name: Install prospector2html
        run: pip install prospector2html
      
      - name: Generate HTML Report
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep
      
      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-html-report
          path: semgrep-report.html
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

